# Generated by Django 2.1.7 on 2019-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190317_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='OwnerFullName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
