# Generated by Django 2.1.7 on 2019-03-30 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sample_ownerfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2019, 3, 30), null=True),
        ),
    ]
