# Generated by Django 2.1.7 on 2019-03-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190330_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='Box',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], help_text='Box 1 is closest to you, Box 3 is farthest', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='BoxColumn',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='BoxRow',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Column',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Row',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='Shelf',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2019, 3, 31), null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='OwnerFullName',
            field=models.CharField(default='', max_length=50, verbose_name='Owner Name'),
        ),
    ]
