# Generated by Django 2.1.7 on 2019-04-23 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='DateString',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 23), null=True),
        ),
    ]
