# Generated by Django 2.1.7 on 2019-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190423_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='DateString',
            field=models.CharField(default='', max_length=50, verbose_name='Date'),
        ),
    ]
